name: publish 

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn generate
      - run: yarn deploy
        env:
          PERMAWEB_KEY: ${{ secrets.PERMAWEB_KEY }}
